// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRzYGPfPNzkZlcPcIGFwYll49toCbl8Uw',
    appId: '1:405081086950:web:e0c24acca8ee2169879427',
    messagingSenderId: '405081086950',
    projectId: 'neo-app-dff1d',
    authDomain: 'neo-app-dff1d.firebaseapp.com',
    storageBucket: 'neo-app-dff1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAyqWvI5-YmfpB9F7Glh9tC5BbFBIs5-A',
    appId: '1:405081086950:android:7387627494085c5b879427',
    messagingSenderId: '405081086950',
    projectId: 'neo-app-dff1d',
    storageBucket: 'neo-app-dff1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngsy3i6p_UNUwjlSJMMMg_spTk4vqsjI',
    appId: '1:405081086950:ios:15ff5374b3d33552879427',
    messagingSenderId: '405081086950',
    projectId: 'neo-app-dff1d',
    storageBucket: 'neo-app-dff1d.firebasestorage.app',
    iosBundleId: 'com.neovote.neovote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAngsy3i6p_UNUwjlSJMMMg_spTk4vqsjI',
    appId: '1:405081086950:ios:15ff5374b3d33552879427',
    messagingSenderId: '405081086950',
    projectId: 'neo-app-dff1d',
    storageBucket: 'neo-app-dff1d.firebasestorage.app',
    iosBundleId: 'com.neovote.neovote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRzYGPfPNzkZlcPcIGFwYll49toCbl8Uw',
    appId: '1:405081086950:web:a41d3b3cc5f30061879427',
    messagingSenderId: '405081086950',
    projectId: 'neo-app-dff1d',
    authDomain: 'neo-app-dff1d.firebaseapp.com',
    storageBucket: 'neo-app-dff1d.firebasestorage.app',
  );
}
